import React from "react";

import "./about.css";

const About = () => {
  return (
    <section className="about-section">
      <div className="about-container">
        <div className="about-title">About Us</div>
        <div className="about-subtext">
          Track Stack aims to build an all-inclusive audio NFT platform that
          focuses on granting artists full autonomy over their work, as well as
          allowing collectors to share in profits generated by the platform. Our
          platform will revolutionize the music NFT space through the use of
          segmented tracks, which we call ‘snippets’. The trading of these
          snippets will allow our users to turn a profit by listening to their
          favorite musicians and creators.
        </div>
        <div className="about-under-text">One For All</div>
        <button>Join Waitlist</button>
      </div>
    </section>
  );
};

export default About;
